server {
    listen 80;
    server_name featurestage.online www.featurestage.online;

    # Специальный location для проверки владения доменом и авто-продления Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Жесткий редирект всего остального трафика на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name featurestage.online www.featurestage.online;

    # Пути к сертификатам Certbot
    ssl_certificate /etc/letsencrypt/live/featurestage.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/featurestage.online/privkey.pem;

    # Базовые настройки безопасности SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Отдача статики Vue приложения
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}