server {
    listen 80;
    server_name localhost;

    # Отдача статики Vue приложения
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Перенаправление всех запросов на index.html для работы Vue Router
        try_files $uri $uri/ /index.html;
    }
}